import type { QSO } from '$lib/logic/types/qso';
import { ADIF_TO_DB_MAP } from './fields';

function adifDate(value: string): string {
	return value.replaceAll('-', '');
}

function adifTime(value: string): string {
	return value.replaceAll(':', '').slice(0, 6);
}

function formatValue(field: string, value: string | number | boolean): string {
	const text = String(value);

	if (field === 'QSO_DATE') {
		return adifDate(text);
	}

	if (field === 'TIME_ON' || field === 'TIME_OFF') {
		return adifTime(text);
	}

	return text;
}

function fieldRecord(field: string, value: string): string {
	return `<${field}:${value.length}>${value}`;
}

export function exportADIF(qsos: QSO[]): string {
	const lines = [
		'Generated by radio',
		'<ADIF_VER:5>3.1.4',
		'<PROGRAMID:5>radio',
		`<PROGRAMVERSION:5>0.0.1`,
		'<EOH>',
		''
	];

	for (const qso of qsos) {
		const fields: string[] = [];

		for (const [adifField, dbFieldName] of Object.entries(ADIF_TO_DB_MAP)) {
			const dbField = dbFieldName as keyof QSO;
			const value = qso[dbField];

			if (value === undefined || value === null || value === '') {
				continue;
			}

			if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
				fields.push(fieldRecord(adifField, formatValue(adifField, value)));
			}
		}

		if (qso.is_eyeball && qso.prop_mode !== 'EYE') {
			fields.push(fieldRecord('IS_EYEBALL', 'Y'));
		}

		lines.push(`${fields.join(' ')} <EOR>`);
	}

	return `${lines.join('\n')}\n`;
}
