import type { QSO } from '$lib/logic/types/qso';
import { DB_TO_ADIF_MAP } from './fields';

function adifDate(isoTs: string): string {
	const match = isoTs.match(/^(\d{4})-(\d{2})-(\d{2})/);
	if (!match) return '';
	return `${match[1]}${match[2]}${match[3]}`;
}

function adifTime(isoTs: string): string {
	const match = isoTs.match(/T(\d{2}):(\d{2}):(\d{2})/);
	if (!match) return '';
	return `${match[1]}${match[2]}${match[3]}`;
}

function fieldRecord(field: string, value: string): string {
	return `<${field}:${value.length}>${value}`;
}

export function exportADIF(qsos: QSO[]): string {
	const lines = [
		'Generated by radio',
		'<ADIF_VER:5>3.1.4',
		'<PROGRAMID:5>radio',
		`<PROGRAMVERSION:5>0.0.1`,
		'<EOH>',
		''
	];

	for (const qso of qsos) {
		const fields: string[] = [];

		if (qso.time_on) {
			const date = adifDate(qso.time_on);
			const time = adifTime(qso.time_on);
			if (date) fields.push(fieldRecord('QSO_DATE', date));
			if (time) fields.push(fieldRecord('TIME_ON', time));
		}

		if (qso.time_off) {
			const dateOff = adifDate(qso.time_off);
			const timeOff = adifTime(qso.time_off);
			if (dateOff) fields.push(fieldRecord('QSO_DATE_OFF', dateOff));
			if (timeOff) fields.push(fieldRecord('TIME_OFF', timeOff));
		}

		const skipFields = new Set(['time_on', 'time_off']);
		for (const [dbField, adifField] of Object.entries(DB_TO_ADIF_MAP)) {
			if (skipFields.has(dbField)) continue;

			const value = qso[dbField as keyof QSO];

			if (value === undefined || value === null || value === '') {
				continue;
			}

			if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
				fields.push(fieldRecord(adifField, String(value)));
			}
		}

		if (qso.is_eyeball && qso.prop_mode !== 'EYE') {
			fields.push(fieldRecord('IS_EYEBALL', 'Y'));
		}

		lines.push(`${fields.join(' ')} <EOR>`);
	}

	return `${lines.join('\n')}\n`;
}
